      INTEGER MM_LUMPED,MM_PETROV_GALERKIN,MM_CONS_UPWIND,
     &MM_SIMPLE_UPWIND,MM_CENTRED,MM_NEW
      PARAMETER(MM_LUMPED=1,MM_PETROV_GALERKIN=2,
     &MM_CONS_UPWIND=3,MM_SIMPLE_UPWIND=4,MM_CENTRED=5,MM_NEW=6)
