      FUNCTION AREA(X,Y,NB,NODES)
      DOUBLE PRECISION AREA
      INTEGER NB,NODES(NB)
      DOUBLE PRECISION X(1),Y(1)
C
C***********************************************************
C
C                                               ROBERT RENKA
C                                       OAK RIDGE NATL. LAB.
C                                             (615) 576-5139
C
C   GIVEN A SEQUENCE OF NB POINTS IN THE PLANE, THIS
C FUNCTION COMPUTES THE AREA BOUNDED BY THE CLOSED POLY-
C GONAL CURVE WHICH PASSES THROUGH THE POINTS IN THE
C SPECIFIED ORDER.  EACH SIMPLE CLOSED CURVE IS POSITIVELY
C ORIENTED (BOUNDS POSITIVE AREA) IF AND ONLY IF THE POINTS
C ARE SPECIFIED IN COUNTERCLOCKWISE ORDER.  THE LAST POINT
C OF THE CURVE IS TAKEN TO BE THE FIRST POINT SPECIFIED, AND
C THUS THIS POINT NEED NOT BE SPECIFIED TWICE.  HOWEVER, ANY
C POINT MAY BE SPECIFIED MORE THAN ONCE IN ORDER TO DEFINE A
C MULTIPLY CONNECTED DOMAIN.
C   THE AREA OF A TRIANGULATION MAY BE COMPUTED BY CALLING
C AREA WITH VALUES OF NB AND NODES DETERMINED BY SUBROUTINE
C BNODES.
C
C INPUT PARAMETERS -   X,Y - N-VECTORS OF COORDINATES OF
C                            POINTS IN THE PLANE FOR N .GE.
C                            NB.  NODE I HAS COORDINATES
C                            (X(I),Y(I)) FOR I = 1, 2, ...,
C                            N.
C
C                       NB - LENGTH OF NODES.
C
C                    NODES - VECTOR OF NODE INDICES IN THE
C                            RANGE 1 TO N DEFINING THE
C                            POLYGONAL CURVE.
C
C INPUT PARAMETERS ARE NOT ALTERED BY THIS FUNCTION.
C
C OUTPUT PARAMETER -  AREA - SIGNED AREA BOUNDED BY THE
C                            POLYGONAL CURVE DEFINED
C                            ABOVE.
C
C MODULES REFERENCED BY AREA - NONE
C
C***********************************************************
C
      INTEGER NNB,ND,I
      DOUBLE PRECISION A,X0,Y0,DX1,DY1,DX2,DY2
C
C LOCAL PARAMETERS -
C
C NNB =     LOCAL COPY OF NB
C ND =      ELEMENT OF NODES
C I =       DO-LOOP AND NODES INDEX
C A =       PARTIAL SUM OF SIGNED (AND DOUBLED) TRIANGLE
C             AREAS
C X0,Y0 =   X(NODES(1)), Y(NODES(1))
C DX1,DY1 = COMPONENTS OF THE VECTOR NODES(1)-NODES(I) FOR
C             I = 2, 3, ..., NB-1
C DX2,DY2 = COMPONENTS OF THE VECTOR NODES(1)-NODES(I) FOR
C             I = 3, 4, ..., NB
C
      NNB = NB
      A = 0.D0
      IF (NNB.LT.3) GOTO 2
C
C INITIALIZATION
C
      ND = NODES(1)
      X0 = X(ND)
      Y0 = Y(ND)
      ND = NODES(2)
      DX1 = X(ND) - X0
      DY1 = Y(ND) - Y0
C
C LOOP ON TRIANGLES (NODES(1),NODES(I),NODES(I+1)),
C   I = 2, 3, ..., NB-1, ADDING TWICE THEIR SIGNED
C   AREAS TO A
C
      DO 1 I = 3,NNB
          ND = NODES(I)
          DX2 = X(ND) - X0
          DY2 = Y(ND) - Y0
          A = A + DX1*DY2 - DX2*DY1
          DX1 = DX2
          DY1 = DY2
    1 CONTINUE
C
C A CONTAINS TWICE THE SIGNED AREA OF THE REGION
C
    2 AREA = A/2.D0
      RETURN

      END
