      INTEGER FUNCTION BISRCH ( N, K, L )                               BISR0010
C
C ... BISRCH IS AN INTEGER FUNCTION WHICH USES A BISECTION SEARCH
C     TO FIND THE ENTRY J IN THE ARRAY K SUCH THAT THE VALUE L IS
C     GREATER THAN OR EQUAL TO K(J) AND STRICTLY LESS THAN K(J+1).
C
C ... PARAMETER LIST:
C
C          N      INTEGER LENGTH OF VECTOR K
C          K      INTEGER VECTOR
C          L      INTEGER CONSTANT SUCH THAT  K(J) .GE. L .LT. K(J+1)
C                 WITH J RETURNED AS VALUE OF INTEGER FUNCTION BISRCH
C
C ... SPECIFICATIONS FOR ARGUMENTS
C
      INTEGER N, L, K(N)
C
C ... SPECIFICATIONS FOR LOCAL VARIABLES
C
      INTEGER JLEFT, JMID, JRIGHT
C
         JLEFT = 1
         JRIGHT = N
         IF ( N .EQ. 2 ) GO TO 40
         JMID = ( N + 1 ) / 2
C
   10    IF ( L .GE. K(JMID) ) GO TO 20
C
C ...... L .GE. K(LEFT)  AND  L .LT. K(JMID)
C
            JRIGHT = JMID
            GO TO 30
C
C ...... L .GE. K(JMID)  AND  L .LT. K(JRIGHT)
C
   20       JLEFT = JMID
C
C ...... TEST FOR CONVERGENCE
C
   30       IF ( JRIGHT - JLEFT .EQ. 1 ) GO TO 40
            JMID = JLEFT + ( JRIGHT - JLEFT + 1 ) / 2
            GO TO 10
C
C ...... BISECTION SEARCH FINISHED
C
   40    BISRCH = JLEFT
C
         RETURN
      END
