      INTEGER NSCHEME,LDASCHEME,LDA2SCHEME,LWSCHEME,LW2SCHEME,
     &        NLSCHEME,NL2SCHEME,NSSCHEME,PSISCHEME,FCTSCHEME
      PARAMETER(NSCHEME=1,LDASCHEME=2,LDA2SCHEME=2,LWSCHEME=2,LW2SCHEME=2,
     &        NLSCHEME=2,NL2SCHEME=2,NSSCHEME=2,PSISCHEME=2,FCTSCHEME=2)
