      SUBROUTINE E9RINT(MESSG,NW,NERR,SAVE)                             ERRR0000
C
C  THIS ROUTINE STORES THE CURRENT ERROR MESSAGE OR PRINTS THE OLD ONE,
C  IF ANY, DEPENDING ON WHETHER OR NOT SAVE = .TRUE. .
C
      INTEGER MESSG(NW)
      LOGICAL SAVE
C
C  MESSGP STORES AT LEAST THE FIRST 72 CHARACTERS OF THE PREVIOUS
C  MESSAGE. ITS LENGTH IS MACHINE DEPENDENT AND MUST BE AT LEAST
C
C       1 + 71/(THE NUMBER OF CHARACTERS STORED PER INTEGER WORD).
C
      INTEGER MESSGP(36),FMT(14),CCPLUS
C
C  START WITH NO PREVIOUS MESSAGE.
C
      DATA MESSGP(1)/1H1/, NWP/0/, NERRP/0/
C
C  SET UP THE FORMAT FOR PRINTING THE ERROR MESSAGE.
C  THE FORMAT IS SIMPLY (A1,14X,72AXX) WHERE XX=I1MACH(6) IS THE
C  NUMBER OF CHARACTERS STORED PER INTEGER WORD.
C
      DATA CCPLUS  / 1H+ /
C
      DATA FMT( 1) / 1H( /
      DATA FMT( 2) / 1HA /
      DATA FMT( 3) / 1H1 /
      DATA FMT( 4) / 1H, /
      DATA FMT( 5) / 1H1 /
      DATA FMT( 6) / 1H4 /
      DATA FMT( 7) / 1HX /
      DATA FMT( 8) / 1H, /
      DATA FMT( 9) / 1H7 /
      DATA FMT(10) / 1H2 /
      DATA FMT(11) / 1HA /
      DATA FMT(12) / 1HX /
      DATA FMT(13) / 1HX /
      DATA FMT(14) / 1H) /
C
      IF (.NOT.SAVE) GO TO 20
C
C  SAVE THE MESSAGE.
C
        NWP=NW
        NERRP=NERR
        DO 10 I=1,NW
 10     MESSGP(I)=MESSG(I)
C
        GO TO 30
C
 20   IF (I8SAVE(1,0,.FALSE.).EQ.0) GO TO 30
C
C  PRINT THE MESSAGE.
C
        IWUNIT=I1MACH(4)
        WRITE(IWUNIT,9000) NERRP
 9000   FORMAT(7H ERROR ,I4,4H IN )
C
        CALL S88FMT(2,I1MACH(6),FMT(12))
        WRITE(IWUNIT,FMT) CCPLUS,(MESSGP(I),I=1,NWP)
C
 30   RETURN
C
      END
