      SUBROUTINE ISTKIN(NITEMS,ITYPE)                                   STKF0000
C
C  INITIALIZES THE STACK ALLOCATOR, SETTING THE LENGTH OF THE STACK.
C
C  ERROR STATES -
C
C    1 - NITEMS .LE. 0
C    2 - ITYPE .LE. 0 .OR. ITYPE .GE. 6
C
      LOGICAL INIT
C
      DATA INIT/.TRUE./
C
      IF (NITEMS.LE.0) CALL SETERR(20HISTKIN - NITEMS.LE.0,20,1,2)
C
      IF (ITYPE.LE.0.OR.ITYPE.GE.6) CALL SETERR
     1   (33HISTKIN - ITYPE.LE.0.OR.ITYPE.GE.6,33,2,2)
C
      IF (INIT) CALL I0TK00(INIT,NITEMS,ITYPE)
C
      RETURN
C
      END
