      DOUBLE PRECISION FUNCTION SUTHERLAW( M_INFTY, ABAR, ASQR )
C
      IMPLICIT NONE
C
      DOUBLE PRECISION M_INFTY,ABAR,ASQR
      DOUBLE PRECISION TEMP
C
      TEMP = M_INFTY*M_INFTY
      SUTHERLAW = 1.404D0*(M_INFTY*TEMP)*ABAR*ASQR/(TEMP*ASQR+0.404D0)
C
      RETURN
      END
