module test_edney_type1
! Issue #25 (WP-A/M5) task 4, demonstration slice: an Edney Type I
! shock-on-bow-shock interaction on the actual CircularCylinder
! geometry, built from the case's own real bow-shock data (not an
! abstract construction) and verified via co_uqp.
!
! Building a full Edney Type I-VI test MATRIX (varying impinging-shock
! strength/position across all six types) turned out to be blocked by a
! real tooling gap, not just a scoping choice: every existing crossing-
! shock case in this repo (SSInteractions1-2/2-2) has its quadruple
! point ALREADY fully formed in its t=0 sh00.dat -- there is no
! initial-condition generator in this repo that constructs a valid
! special-point configuration for a NEW geometry from scratch, and
! ch_sh_topology.f (issue #24/E4) only implements the FWP->RR topology
! transition, not general new-special-point formation during a run. So
! a real matrix needs either that generator tool or hand-building each
! case's mesh + initial special points individually -- out of scope for
! this increment. This test demonstrates the analytic half of that
! (the crossing-shock construction itself, at the co_uqp kernel level)
! on real case data, without attempting the mesh/file engineering that
! would be needed to actually run it end-to-end.
!
! CircularCylinder's freestream is M=20 (rho=1, p=0.0017857, u=-1, v=0
! -- read directly from tests/CircularCylinder/sh00.dat), and its
! existing bow shock (the case's own converged initial condition) has a
! post-shock Mach of 1.704 at point 34 (x=0.882, y=1.553), safely on the
! supersonic side of the bow shock's sonic point (which sits between
! points 26 and 30 in that same file, M_down going from 0.686 to 1.208).
!
! An impinging shock, generated by a notional 15-degree wedge in the
! same M=20 freestream, is aimed to cross the bow shock at that point.
! Both resulting transmitted shocks are then constructed via the SAME
! shared-downstream-direction technique as test_three_shock_theory.f90
! (reused verbatim, not reimplemented): each leg's own upstream state --
! the bow shock's ACTUAL recorded post-shock state for one leg, the
! impinging shock's computed post-shock state for the other -- is turned
! toward a common downstream flow direction, with one leg's base
! pressure solved in closed form so the slip-line pressure-matching
! condition holds exactly. Both resulting downstream Mach numbers stay
! above 1 (1.245 and 4.44) -- the hallmark of Edney Type I (a "simple"
! shock crossing with two continuing supersonic transmitted shocks and a
! slip line, as opposed to Types II-VI, which involve an embedded
! subsonic pocket, a free shear layer, or a supersonic jet impinging on
! the body -- none of which the current special_point_t repertoire has
! a dedicated type for; see mod_special_point.f90's type list).
!
! Construction verified numerically (all residuals ~1e-15) via a
! standalone Python script before writing the Fortran below, same
! discipline as test_two_shock_theory.f90/test_three_shock_theory.f90.
  use mod_kinds, only: wp, i4
  use mod_constants, only: naddholesmax, ndim, nprdbndmax
  use testdrive, only: new_unittest, unittest_type, error_type, check
  implicit none(type, external)
  private
  public :: collect_edney_type1

  real(wp), parameter :: pi = 3.14159265358979323846_wp

contains

  subroutine collect_edney_type1(testsuite)
    type(unittest_type), allocatable, intent(out) :: testsuite(:)

    testsuite = [&
    &new_unittest("bow_shock_impingement_is_edney_type1", test_edney1)&
    &]
  end subroutine collect_edney_type1

  real(wp) function theta_from_beta(beta, M, gam) result(theta)
    real(wp), intent(in) :: beta, M, gam
    theta = atan(2.0_wp/tan(beta)*(M**2*sin(beta)**2 - 1.0_wp)/&
    &(M**2*(gam + cos(2.0_wp*beta)) + 2.0_wp))
  end function theta_from_beta

  real(wp) function solve_beta_weak(M, theta, gam) result(beta)
    real(wp), intent(in) :: M, theta, gam
    real(wp) :: lo, hi, mid, flo, fmid
    integer(i4), parameter :: n_bisect = 100
    integer(i4) :: i

    lo = asin(1.0_wp/M) + 1.0e-6_wp
    hi = pi/2.0_wp - 1.0e-6_wp
    flo = theta_from_beta(lo, M, gam) - theta
    do i = 1, n_bisect
      mid = 0.5_wp*(lo + hi)
      fmid = theta_from_beta(mid, M, gam) - theta
      if (flo*fmid <= 0.0_wp) then
        hi = mid
      else
        lo = mid; flo = fmid
      end if
    end do
    beta = 0.5_wp*(lo + hi)
  end function solve_beta_weak

  subroutine oblique_jump(M1, beta, gam, p_ratio, rho_ratio, M2)
    real(wp), intent(in) :: M1, beta, gam
    real(wp), intent(out) :: p_ratio, rho_ratio, M2
    real(wp) :: Mn1, delta, Mn2sq, theta

    Mn1 = M1*sin(beta)
    delta = (gam - 1.0_wp)/2.0_wp
    p_ratio = 1.0_wp + 2.0_wp*gam/(gam + 1.0_wp)*(Mn1**2 - 1.0_wp)
    rho_ratio = (gam + 1.0_wp)*Mn1**2/((gam - 1.0_wp)*Mn1**2 + 2.0_wp)
    Mn2sq = (1.0_wp + delta*Mn1**2)/(gam*Mn1**2 - delta)
    theta = theta_from_beta(beta, M1, gam)
    M2 = sqrt(Mn2sq)/sin(beta - theta)
  end subroutine oblique_jump

! Same helper as test_three_shock_theory.f90's shock_leg: one shock leg
! turning its own upstream (M_up, phi_up, rom, pm) toward phi_common.
  subroutine shock_leg(M_up, phi_up, rom, pm, phi_common, gam,&
  &u_up, v_up, ro_dn, p_dn, u_dn, v_dn, sx, M_dn)
    real(wp), intent(in) :: M_up, phi_up, rom, pm, phi_common, gam
    real(wp), intent(out) :: u_up, v_up, ro_dn, p_dn, u_dn, v_dn, sx, M_dn
    real(wp) :: theta, beta, p_ratio, rho_ratio, a_up, a_dn
    real(wp) :: dx, dy, nlen, nx, ny, taux, tauy

    theta = phi_up - phi_common
    beta = solve_beta_weak(M_up, abs(theta), gam)
    call oblique_jump(M_up, beta, gam, p_ratio, rho_ratio, M_dn)

    p_dn = pm*p_ratio
    ro_dn = rom*rho_ratio
    a_up = sqrt(gam*pm/rom)
    a_dn = sqrt(gam*p_dn/ro_dn)

    u_up = M_up*a_up*cos(phi_up); v_up = M_up*a_up*sin(phi_up)
    u_dn = M_dn*a_dn*cos(phi_common); v_dn = M_dn*a_dn*sin(phi_common)

    dx = u_up - u_dn; dy = v_up - v_dn
    nlen = sqrt(dx**2 + dy**2)
    nx = dx/nlen; ny = dy/nlen
    taux = ny; tauy = -nx
    sx = atan2(tauy, taux)
  end subroutine shock_leg

  subroutine test_edney1(error)
    type(error_type), allocatable, intent(out) :: error

    include 'paramt.h'
    external :: co_uqp

    real(wp), parameter :: gam = 1.4_wp
    real(wp), parameter :: phi_common = 152.0_wp*pi/180.0_wp
    ! CircularCylinder's own freestream (tests/CircularCylinder/sh00.dat)
    real(wp), parameter :: rom_fs = 1.0_wp, pm_fs = 0.0017857210857142713_wp
    real(wp), parameter :: M_fs = 20.0_wp
    real(wp), parameter :: phi_fs = pi   ! freestream direction (-1,0)
    ! CircularCylinder's own bow-shock downstream state at point 34
    ! (x=0.882, y=1.553): M=1.704, safely supersonic (sonic point is
    ! between points 26 and 30 in that file)
    real(wp), parameter :: M_A = 1.7037863227283816_wp
    real(wp), parameter :: rom_A = 5.886_wp, pm_A = 0.53874_wp
    real(wp), parameter :: phi_A = 139.38851581579775_wp*pi/180.0_wp
    ! notional 15-degree wedge generating the impinging shock
    real(wp), parameter :: theta_B_gen = 15.0_wp*pi/180.0_wp

    real(wp) :: beta_B_gen, p_ratio_B_gen, rho_ratio_B_gen, M_B, phi_B
    real(wp) :: rom_B, pm_B
    real(wp) :: uA_up, vA_up, roA_dn, pA_dn, uA_dn, vA_dn, sxA, M_dnA
    real(wp) :: uB_up, vB_up, roB_dn, pB_dn, uB_dn, vB_dn, sxB, M_dnB
    real(wp) :: beta_prep, p_ratio_prep, rho_ratio_prep, M_prep
    real(wp) :: pm_B_scaled
    real(wp) :: y(24), yn1(24)

    ga = gam
    gm1 = gam - 1.0_wp

    ! impinging shock: freestream -> its own post-shock state (this is
    ! the "generator" shock itself, computed once via a plain oblique
    ! jump, not a shock_leg -- it doesn't turn toward phi_common, IT
    ! generates the upstream state block B's own shock_leg call turns)
    beta_B_gen = solve_beta_weak(M_fs, theta_B_gen, gam)
    call oblique_jump(M_fs, beta_B_gen, gam, p_ratio_B_gen, rho_ratio_B_gen, M_B)
    pm_B = pm_fs*p_ratio_B_gen
    rom_B = rom_fs*rho_ratio_B_gen
    phi_B = phi_fs - theta_B_gen

    ! block A (transmitted continuation of the bow shock): upstream is
    ! the bow shock's OWN real post-shock state
    call shock_leg(M_A, phi_A, rom_A, pm_A, phi_common, gam,&
    &uA_up, vA_up, roA_dn, pA_dn, uA_dn, vA_dn, sxA, M_dnA)

    ! block B (transmitted continuation of the impinging shock): solve
    ! its base pressure in closed form so pB_dn matches pA_dn exactly
    beta_prep = solve_beta_weak(M_B, abs(phi_B - phi_common), gam)
    call oblique_jump(M_B, beta_prep, gam, p_ratio_prep, rho_ratio_prep, M_prep)
    pm_B_scaled = pA_dn/p_ratio_prep

    call shock_leg(M_B, phi_B, rom_B, pm_B_scaled, phi_common, gam,&
    &uB_up, vB_up, roB_dn, pB_dn, uB_dn, vB_dn, sxB, M_dnB)

    ! Edney Type I signature: both transmitted legs stay supersonic
    call check(error, M_dnA > 1.0_wp,&
    &message="transmitted bow-shock leg is not supersonic -- not Type I")
    if (allocated(error)) return
    call check(error, M_dnB > 1.0_wp,&
    &message="transmitted impinging-shock leg is not supersonic -- not Type I")
    if (allocated(error)) return

    y(1:4) = [rom_A, pm_A, uA_up, vA_up]        ! unused passthrough slot
    y(5:8) = [rom_A, pm_A, uA_up, vA_up]        ! block A upstream: exact
    y(9:12) = [rom_B, pm_B_scaled, uB_up, vB_up] ! block B upstream: exact
    y(13:16) = [1.05_wp*roA_dn, 0.95_wp*pA_dn, 1.05_wp*uA_dn, 1.05_wp*vA_dn]
    y(17:20) = [0.95_wp*roB_dn, 1.05_wp*pB_dn, 0.95_wp*uB_dn, 0.95_wp*vB_dn]
    y(21) = 0.0_wp
    y(22) = sxA - 0.03_wp
    y(23) = 0.0_wp
    y(24) = sxB + 0.02_wp

    call co_uqp(y, 0.0_wp, 0.0_wp, yn1)  ! stationary interaction point

    call check(error, yn1(13), roA_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
    call check(error, yn1(14), pA_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
    call check(error, yn1(15), uA_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
    call check(error, yn1(16), vA_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
    call check(error, yn1(17), roB_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
    call check(error, yn1(18), pB_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
    call check(error, yn1(19), uB_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
    call check(error, yn1(20), vB_dn, rel=.true., thr=1.0e-6_wp)
    if (allocated(error)) return
  end subroutine test_edney1

end module test_edney_type1
